### ISSUE TITLE
Fix color of buttons

### ISSUE THREAD

**Issue by PaliwalSparsh** [PaliwalSparsh/dots-and-boxes#4]
Currently the default color of button is grey. As a result of this, "Start Game" button feels like it is disabled by default with the grey color scheme, and may trick people into thinking they have to do something else before they can start.

Same with the button on Game over screen. We can make the default color of button as orange and onHover and onActive can have darker shade of the same.

**Comment by vlogozzo** [comment]
Im new to the project and would like to take a shot at this

**Comment by PaliwalSparsh** [comment]
@vlogozzo Great work and thankyou for the PR. If you feel like working on another issues I would be more than happy to help. 

One thing that we can improve are commit messages. You can go through this to understand how the structure of commit messages need to be -

[https://nitdgpos.github.io/get_involved#code-practices](https://nitdgpos.github.io/get_involved#code-practices)

Also for git commit message I have been using imperative sense. 
Ex.- PAST TENSE:  changed to a darker color for game start and game reset button
 IMPERATIVE TENSE: Change game start and game reset button to darker theme

Both are correct but just for this project we are using imperative sense. In commit body however its perfectly normal to use past sense.

Anyway I am merging the PR, we are not that big. But its better we start with good practice. I will also try my best adhere to these :)
