### ISSUE TITLE
css file structure and import rework

### ISSUE THREAD

**Issue by vlogozzo** [PaliwalSparsh/dots-and-boxes#7]
with the app running on one page, having different `.css` files only forms a race condition. So whichever `.css` file is imported last wins

Solutions:
condense the CSS into one file 
or 
scrub the HTML header of imports each time a new "scene" in the game is created and re-import the correct CSS file

**Comment by PaliwalSparsh** [comment]
Hi @vlogozzo thanks for creating the issue. It is not a racecondition but normal cascading which is normal behaviour of CSS. What i did to fix it was I created a global.css file where we will be writing all generic CSS for things like buttons, inputs and labels. Again thanks for highlighting the issue :)
